# Copyright (C) 2017 Feedvay (Gagandeep Singh: singh.gagan144@gmail.com) - All Rights Reserved
# Content in this document can not be copied and/or distributed without the express
# permission of Gagandeep Singh.
"""
Django settings for feedvay project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!s!l2vecv-di(y6#@z^!sgztq3@s)8-3sm(e9ci=x$&uro3g2t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# ----- Application definition -----

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.admindocs',

    # Packages
    'django_mysql',
    'django_extensions',
    'easy_select2',
    'django_fsm_log',
    'captcha',
    # 'django_mongoengine',
    'tinymce',
    'fcm',
    'colorful',
    'tree_tag',

    # Apps
    'feedvay',
    'accounts',
    'watchdog',
    'owlery',
    'console',
    'clients',
    'utilities',
    'market',
    'languages',
    'surveys',
    'form_builder',
    'algorithms',
    'storeroom',
    'geography',
    'feedback',
    'critics',
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'console.middleware.OrgConsoleMiddleware',
    'watchdog.middleware.ErrorLogMiddleware',
]

ROOT_URLCONF = 'feedvay.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'feedvay.context_processors.settings_variables'
            ],
        },
    },
]

WSGI_APPLICATION = 'feedvay.wsgi.application'


# ----- Database -----
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': '<mysql_db_name>',
        'USER': '<mysql_user>',
        'PASSWORD': '<mysql_pass>',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            # Tell MySQLdb to connect with 'utf8mb4' character set
            'charset': 'utf8',   # recommended: 'utf8', or 'utf8mb4' for emoji & custom unicode characters
        },
    }
}
SILENCED_SYSTEM_CHECKS = [
    'django_mysql.W003',    # To silent 'utf8mb4' character-set warning
]

# ----- Mongo Database -----
MONGO_DATABASE = {
    "HOST": "127.0.0.1",
    "PORT": 27017,
    "NAME": "<mongo_db_name>"
}
# Connect to MongoDB
from mongoengine.connection import connect
connect(
    db = MONGO_DATABASE["NAME"],
    host = MONGO_DATABASE["HOST"],
    port = MONGO_DATABASE["PORT"],
    # read_preference = ReadPreference.NEAREST
)


# ----- Password validation -----
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# ----- Internationalization -----
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC' #'Asia/Kolkata' #'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# ----- Session -----
# For all cases
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# For staff users (Django admin)
SESSION_COOKIE_AGE = 8*60*60     # In seconds

# For web portal users
SESSION_COOKIE_AGE_PUBLIC = 7*24*60*60  # In seconds

# ----- AWS -----
AWS_STORAGE_BUCKET_NAME = 'testing.in.feedvay.com'
# AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
AWS_S3_CUSTOM_DOMAIN = 's3-us-west-2.amazonaws.com/%s' % AWS_STORAGE_BUCKET_NAME
# AWS_S3_CUSTOM_DOMAIN = AWS_STORAGE_BUCKET_NAME
AWS_ACCESS_KEY_ID = '<aws_access_key>'
AWS_SECRET_ACCESS_KEY = '<aws_secret_key>'

# ----- Static files (CSS, JavaScript, Images) -----
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# ----- Media -----
# MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# MEDIA_URL = '/media/'
MEDIAFILES_LOCATION = ''
MEDIA_URL = "http://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)
DEFAULT_FILE_STORAGE = 'utilities.custom_storages.MediaStorage'


# ----- Add SVG to Mime-Types -----
import mimetypes
mimetypes.add_type("image/svg+xml", ".svg", True)
mimetypes.add_type("image/svg+xml", ".svgz", True)

# ----- Organization color & skin -----
# This usually does not change frequently. However, incase of a change
# edit '/templates/theme/*-style-template.css' and execute command
# 'python manage.py feedvay_update_main_skin'. This will override
# '/static/ui/css/style-default.css' file. DO NOT make changes in
# '/static/ui/css/style-default.css' file. This will be overridden.
THEME_DEFAULT = {
    "primary": "#2a94db",
    "primary_dark": "#1a7bb9",
    "primary_disabled": "#6eb7e6"
}

# ----- General project settings -----
FEEDVAY_DOMAIN = 'http://www.feedvay.com'
LOGIN_URL_STAFF = '/admin/login/'
REGISTRATION_OPEN = True

JWT_ALOG = 'HS256'
JWT_SECRET_KEY = 'be16bad4-5c8b-4482-a7f0-e2ab0f70b088'

# # ----- Caching -----
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, "CACHE"),
    }
}

# ----- Accounts -----
VERIFICATION_EXPIRY = 15*60 # In seconds

# ----- ReCaptcha -----
RECAPTCHA_PUBLIC_KEY = '<recaptcha_public_key>'
RECAPTCHA_PRIVATE_KEY = '<recaptcha_private_key>'
NOCAPTCHA = True
# RECAPTCHA_PROXY = 'http://127.0.0.1:8000'

# ----- Documentation -----
DOCS_PATH = os.path.join(BASE_DIR, "docs/build/html")

# ----- Watchdog -----
WATCHDOG_ERRORLOG_ENABLED = True

# ----- Owlery -----
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '<host_email_id>'
EMAIL_HOST_PASSWORD = open( os.path.join(BASE_DIR,'email_pass.txt')).read()

SMS_HOST_NUMBER = '+91999999'

NOTIF_EXPIRY = 30   # In days

# ----- Firebase Cloud Messaging -----
FCM_APIKEY = "<fcm_api_key>"
FCM_DEVICE_MODEL = 'accounts.UserDevice'
FCM_MAX_RECIPIENTS = 20

# ----- TinyMCE Django admin -----
TINYMCE_DEFAULT_CONFIG = {
    'plugins': "table,spellchecker,paste,searchreplace",
    'theme': "advanced",
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 10,
    'width': '100%',
    'theme_advanced_resizing' : True,
}

# ----- Form Builder -----
DEFAULT_COLOR = THEME_DEFAULT["primary"]  # Usage:- ThemeSkin: for default skin color
DEFAULT_FORM_THEME = {
    'theme_code': 'bootstrap_3',
    'skin_code': 'default'
}

# ----- Google Map API ----
API_GOOGLE_MAP = "<google_api_key>"

# ----- Indicoio -----
INDICOIO_API_KEY = '<indicoio_api_key>'