# Copyright (C) 2016 Feedvuy (Gagandeep Singh: singh.gagan144@gmail.com) - All Rights Reserved
# Content in this document can not be copied and/or distributed without the express
# permission of Gagandeep Singh.
"""
Django settings for feedvuy project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!s!l2vecv-di(y6#@z^!sgztq3@s)8-3sm(e9ci=x$&uro3g2t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# ----- Application definition -----

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.admindocs',

    # Packages
    'django_mysql',
    'django_extensions',
    'easy_select2',
    'django_fsm_log',
    'captcha',

    # Apps
    'accounts',
    'watchdog',
    'owlery',
    'console',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'watchdog.middleware.ErrorLogMiddleware',
]

ROOT_URLCONF = 'feedvuy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'feedvuy.wsgi.application'


# ----- Database -----
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'feedvuy',
        'USER': 'root',
        'PASSWORD': '!root1234@',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            # Tell MySQLdb to connect with 'utf8mb4' character set
            'charset': 'utf8',   # recommended: 'utf8', or 'utf8mb4' for emoji & custom unicode characters
        },
    }
}
SILENCED_SYSTEM_CHECKS = [
    'django_mysql.W003',    # To silent 'utf8mb4' character-set warning
]

# ----- Mongo Database -----
# MONGO_DATABASE = {
#     "HOST": "127.0.0.1",
#     "PORT": 27017,
#     "NAME": "feedvuy"
# }


# ----- Password validation -----
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# ----- Internationalization -----
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# ----- Session -----
# For all cases
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# For staff users (Django admin)
SESSION_COOKIE_AGE = 8*60*60     # In seconds

# For web portal users
SESSION_COOKIE_AGE_PUBLIC = 24*60*60  # In seconds

# ----- Static files (CSS, JavaScript, Images) -----
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# ----- Media -----
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = '/media/'


# ----- Add SVG to Mime-Types -----
import mimetypes
mimetypes.add_type("image/svg+xml", ".svg", True)
mimetypes.add_type("image/svg+xml", ".svgz", True)

# ----- General project settings -----
LOGIN_URL_STAFF = '/admin/login/'
REGISTRATION_OPEN = True

JWT_ALOG = 'HS256'
JWT_SECRET_KEY = 'be16bad4-5c8b-4482-a7f0-e2ab0f70b088'

# ----- Accounts -----
VERIFICATION_EXPIRY = 15*60 # In seconds

# ----- ReCaptcha -----
RECAPTCHA_PUBLIC_KEY = '6LftyggUAAAAAG2J4egQHiCfdDIKr0VH9LmqkYmG'
RECAPTCHA_PRIVATE_KEY = '6LftyggUAAAAAMn37jxqIe8E51c1s9LqMGhQLGMT'
NOCAPTCHA = True
# RECAPTCHA_PROXY = 'http://127.0.0.1:8000'

# ----- Documentation -----
DOCS_PATH = os.path.join(BASE_DIR, "docs/build/html")

# ----- Watchdog -----
WATCHDOG_ERRORLOG_ENABLED = True

# ----- Owlery -----
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'gagandeep.taurus91@gmail.com'
EMAIL_HOST_PASSWORD = open( os.path.join(BASE_DIR,'email_pass.txt')).read()

SMS_HOST_NUMBER = '+91999999'